### ISSUE TITLE
[question] Question about the use of image features in the model “ST_Transformer_adaptive”

### ISSUE THREAD

**Issue by RKrnn** [Zhaocy-Research/TransformerST#1]
Hi! I find that there is no image feature involved during the training step of the model “ST_Transformer_adaptive”, which is inconsistent with the statement  "The proposed method makes it possible to incorporate the heterogeneous spatial gene expression with histology image using multimodal data" mentioned in the paper. I wonder if there are deviations in my understanding of the article or in some ways I misunderstanding the code.

**Comment by Zhaocy-Research** [comment]
Hi @RKrnn, 

Thanks so much for using our TransformerST. The histology image is used to reconstruct the graph relationship in the function Mouse_Lung_histology.py. We provide some solutions to combine the histology image with gene expression in the function TransformerST_graph_func.py. In addition, as shown in IDC_super_TransformerST.py, the histology image is used in the super-resolution task.
